# Generated by Django 3.2.9 on 2022-01-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='introduction',
            field=models.CharField(default='自己紹介は現在登録されていません', max_length=255, verbose_name='自己紹介'),
        ),
    ]
